name: hello-world
on: push
jobs:
  my-job:
    runs-on: 
      -self-hosted
    steps:
      - name: my-step
        run: |
          curl ipinfo.io/ip
          echo `curl ipinfo.io/ip`
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
